name: Backend Tests

on:
  pull_request:
    branches: [main]
    paths: ['backend/**']

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./backend
    
    - name: Run tests
      run: npm test -- --coverage --coverageReporters=json-summary
      working-directory: ./backend
    
    - name: Comment PR with test results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = './backend/coverage/coverage-summary.json';
          
          let comment = '## Backend Test Results 🧪\n\n';
          
          if (fs.existsSync(path)) {
            const coverage = JSON.parse(fs.readFileSync(path));
            comment += `| Metric | Coverage |\n`;
            comment += `|--------|----------|\n`;
            comment += `| Lines | ${coverage.total.lines.pct}% |\n`;
            comment += `| Functions | ${coverage.total.functions.pct}% |\n`;
            comment += `| Branches | ${coverage.total.branches.pct}% |\n`;
            comment += `| Statements | ${coverage.total.statements.pct}% |\n`;
          } else {
            comment += '✅ All tests passed!\n';
          }
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });