name: Destroy Infrastructure

on:
  workflow_dispatch:
jobs:
  destroy:
    name: Destroy CDK Stack
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js and dependencies
      working-directory: ./cdk
      run: |
        npm install -g aws-cdk
        npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: 'af-south-1'

    - name: Destroy CDK Stack
      working-directory: ./cdk
      run: |
        npx cdk destroy  --force